app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('user_index/<int:num>/', views.user_index, name='user_index'),
    path('user_detail/<int:pk>/', views.user_detail, name='user_detail'),
    path('match_index/<int:num>/', views.match_index, name='match_index'),
    path('match_detail/<int:pk>/', views.match_detail, name='match_detail'),
    path('submit_deck/<int:pk>/', views.submit_deck, name='submit_deck'),
    path('register_match/', views.register_match, name='register_match'),
    path('submit_result/<int:pk>/', views.submit_result, name='submit_result'),
    path('edit_match/<int:pk>/', views.edit_match, name='edit_match'),
    path('delete_match/<int:pk>/', views.delete_match, name='delete_match'),
    path('deckthema_index/', views.deckthema_index, name='deckthema_index'),
    path('deckthema_detail/<int:pk>/', views.deckthema_detail, name='deckthema_detail'),
    path('deck_records/', views.deck_records, name='deck_records'),
    path('rank/', views.rank, name='rank'),
]

league_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>海賊リーグ</title>
</head>
<body>
<header>
    <div class="container">
        <div class="header-menu">
        <a href="{% url 'app:index' %}">海賊リーグ</a>
        <a href="{% url 'app:user_index' 1 %}">ユーザー一覧</a>
        <a href="{% url 'app:match_index' 1 %}">試合一覧</a>
        <a href="{% url 'app:deck_records' %}">相性表</a>
        <a href="{% url 'app:rank' %}">順位表</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'app:user_detail' request.user.pk %}">マイページ</a>
            <a href="{% url 'app:logout' %}">ログアウト</a>
            @{{request.user.username}}
        {% else %}
            <a href="{% url 'app:login' %}">ログイン</a>
            <a href="{% url 'app:signup' %}">登録</a>
        {% endif %}
        </div>
    </div>
</header>

<div class="container">
    {% for message in messages %}
        <p class="message-success">{{ message }}</p>
    {% endfor %}
    {% block content %}{% endblock  %}
</div>

</body>
</html>

app/templates/app/deck_records.html
{% extends 'app/base.html' %}

{% block content %}
    <h2>相性表</h2>
    {{win_lose}}
    {{rates}}
{% endblock content %}

app/templates/app/deckthema_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h2>{{deck.name}}</h2>
    <img src="{{deck.image.url}}">
    <p>tier{{deck.tier}}</p>
    <p>使用回数 {{deck.in_played}}</p>
    <p>{{deck.win}}勝 {{deck.lose}}敗</p>
{% endblock content %}

app/templates/app/deckthema_index.html
{% extends 'app/base.html' %}

{% block content %}
    {% for deck in decks %}
        <a href="{% url 'app:deckthema_detail' deck.pk %}">
            <h3>{{deck.name}}</h3>
            <img src="{{deck.image.url}}">
        </a>
        <p>tier{{deck.tier}}</p>
    {% endfor %}
{% endblock content %}

app/templates/app/edit_match.html
{% extends 'app/base.html' %}

{% block content %}
<p>試合編集</p>
<form action="{% url 'app:edit_match' match.pk %}" method="POST">{% csrf_token %}
    <table>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
        <tr>
            <th>相手</th>
            <td>{{ form.player2 }}</td>
        </tr>
    </table>
    <button type="submit" class="btn">登録</button>
</form>

{% endblock content %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
[海賊リーグ概要]
{% endblock  %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}
<form class="form-signin" method="POST">{% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名かパスワードが間違っています。</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>名前</label>
    <input name="username"> <!-- emailではない-->
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>
{% endblock  %}

app/templates/app/match_index.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="register_match">
        <a href="{% url 'app:register_match' %}">試合登録</a>
    </div>
    <div class="match_wrapper">
        {% for match in matches %}
            <div class="match_content">
                <a href="{% url 'app:match_detail' match.pk %}">{{ match }}</a>
                {% if request.user == match.player1 or request.user == match.player2 %}
                        <p><a href="{% url 'app:submit_result' match.pk %}">結果報告</a></p>
                {% endif %}
                {% if request.user == match.player1 %}
                        <p><a href="{% url 'app:edit_match' match.pk %}">日程編集</a></p>
                        <form action="{% url 'app:delete_match' match.pk%}" method="POST">{% csrf_token %}
                            <button type="submit" onclick="return confirm('本当に削除しますか？');">削除</button>
                        </form>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <table>
            <tr>
                {% if matches.has_previous %}
                    <th>
                        <a class="page-link" href="{% url 'app:match_index' 1 %}">&laquo; first</a>
                    </th>
                    <th>
                        <a class="page-link" href="{% url 'app:match_index' matches.previous_page_number %}">&laquo; prev</a>
                    </th>
                {% else %}
                    <th>
                        <a class="page-link">&laquo; first</a>
                    </th>
                    <th>
                        <a class="page-link">&laquo; prev</a>
                    </th>
                {% endif %}
                    <th>
                        <a class="page-link">{{matches.number}}/{{matches.paginator.num_pages}}</a>
                    </th>
                {% if matches.has_next %}
                    <th>
                        <a class="page-link" href="{% url 'app:match_index' matches.next_page_number %}">next &raquo;</a>
                    </th>
                    <th>
                        <a class="page-link" href="{% url 'app:match_index' matches.paginator.num_pages %}">last &raquo;</a>
                    </th>
                {% else %}
                    <th>
                        <a class="page-link">next &raquo;</a>
                    </th>
                    <th>
                        <a class="page-link">last &raquo;</a>
                    </th>
                {% endif %}
            </tr>
        </table>
    </div>
{% endblock  %}

app/templates/app/rank.html
{% extends 'app/base.html' %}

{% block content %}
    <table>
    <tr><th>名前</th><th>勝</th><th>負</th><th>得点</th></tr>
    {% for record in records %}
        <tr><td>{{record.user}}</td><td>{{record.win}}</td><td>{{record.lose}}</td><td>{{record.point}}</td></tr>
    {% endfor %}
    </table>
{% endblock content %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<h2>ユーザー登録</h2>

<form action="{% url 'app:signup' %}" method="POST">{% csrf_token %}
    <label>名前</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <input type="submit" value="登録する">
</form>

{% endblock  %}

app/templates/app/submit_deck.html
{% extends 'app/base.html' %}

{% block content %}
<p>「{{ match }}」デッキ提出</p>
<form action="{% url 'app:submit_deck' match.pk %}" method="POST" enctype="multipart/form-data">{% csrf_token %}

    <table>
        <tr>
            <th>デッキ画像1</th>
            <td>{{ form.image1 }}</td>
        </tr>
        <tr>
            <th>デッキ画像2</th>
            <td>{{ form.image2 }}</td>
        </tr>
    </table>
    <button type="submit" class="btn">提出</button>
</form>
{% endblock  %}

app/templates/app/submit_result.html
{% extends 'app/base.html' %}

{% block content %}
    <form action="{% url 'app:submit_result' match.pk %}" method="POST">{% csrf_token %}
        <table>
            <tr>
                <th>デッキ名</th>
                <td>{{ form.deck }}</td>
            </tr>
            <tr>
                <th>スキル</th>
                <td>{{ form.skill }}</td>
            </tr>
            <tr>
                <th>1試合目</th>
                <td>{{ form.result1 }}</td>
            </tr>
            <tr>
                <th>2試合目</th>
                <td>{{ form.result2 }}</td>
            </tr>
            <tr>
                <th>3試合目</th>
                <td>{{ form.result3 }}</td>
            </tr>
            <tr>
                <th>コメント(任意)</th>
                <td>{{ form.comment }}</td>
            </tr>
        </table>
        <button type="submit" class="btn">提出</button>
    </form>
{% endblock  %}

app/templates/app/user_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <p>{{ user }}のマイページ</p>
    {% if user.pk == request.user.pk %}
        <p><a href="{% url 'app:register_match' %}">試合登録</a></p>
        {% for match in matches %}
            <p><a href="{% url 'app:submit_deck' match.pk %}">「{{match}}」 デッキ提出</a></p>
        {% endfor %}
    {% else %}
        {% for match in matches %}
            <p><a href="{% url 'app:match_detail' match.pk %}">{{ match }}</a></p>
        {% endfor %}
    {% endif %}
    {% if user.pk == request.user.pk or request.user.is_superuser  %}
        {% for deck in decks %}
            <div class="deck_image">
                <p>{{deck.match}}</p>
                <img src="{{ deck.image1.url }}" width="200px" height="200px">
                {% if deck.image2 %}
                    <img src="{{ deck.image2.url }}" width="200px" height="200px">
                {% endif %}
            </div>
        {% endfor %}
    {% endif %}
{% endblock  %}

app/templates/app/user_index.html
{% extends 'app/base.html' %}

{% block content %}
    <form action="{%url 'app:user_index' 1 %}" method="post">{% csrf_token %}
        {{form}}
        <button type="submit">検索</button>
    </form>
        <div class="user_wrapper">
            {% for user_image in user_images %}
                <div class="user_info">
                    <img src="{{user_image.image.url}}" width="50px" height="50px">
                    <a href="{% url 'app:user_detail' user_image.user.pk %}">{{ user_image.user.username }}</a>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
        <table>
            <tr>
                {% if user_images.has_previous %}
                    <th>
                        <a class="page-link" href="{% url 'app:user_index' 1 %}">&laquo; first</a>
                    </th>
                    <th>
                        <a class="page-link" href="{% url 'app:user_index' user_images.previous_page_number %}">&laquo; prev</a>
                    </th>
                {% else %}
                    <th>
                        <a class="page-link">&laquo; first</a>
                    </th>
                    <th>
                        <a class="page-link">&laquo; prev</a>
                    </th>
                {% endif %}
                    <th>
                        <a class="page-link">{{user_images.number}}/{{user_images.paginator.num_pages}}</a>
                    </th>
                {% if user_images.has_next %}
                    <th>
                        <a class="page-link" href="{% url 'app:user_index' user_images.next_page_number %}">next &raquo;</a>
                    </th>
                    <th>
                        <a class="page-link" href="{% url 'app:user_index' user_images.paginator.num_pages %}">last &raquo;</a>
                    </th>
                {% else %}
                    <th>
                        <a class="page-link">next &raquo;</a>
                    </th>
                    <th>
                        <a class="page-link">last &raquo;</a>
                    </th>
                {% endif %}
            </tr>
        </table>
    </div>
{% endblock  %}